version: "2"
    
services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 258wsndx23
      MYSQL_DATABASE: gtnh
      MYSQL_USER: gtnh
      MYSQL_PASSWORD: gtnh
  grafana:
    depends_on:
      - db
    image: grafana/grafana
    user: "0"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
  control:
    depends_on:
      - db
    image: control
    ports:
      - 8080:8080

