version: "3.3"
    
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gtnh
      MYSQL_USER: gtnh
      MYSQL_PASSWORD: gtnh
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

